/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SeedRouteImport } from './routes/seed'
import { Route as SanityRouteImport } from './routes/sanity'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DebugSimpleRouteImport } from './routes/debug-simple'
import { Route as DebugDbRouteImport } from './routes/debug-db'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CorporationsIndexRouteImport } from './routes/corporations/index'
import { Route as ProfilesIdRouteImport } from './routes/profiles.$id'
import { Route as PostsSlugRouteImport } from './routes/posts/$slug'
import { Route as PostsIdRouteImport } from './routes/posts.$id'
import { Route as FundsIdRouteImport } from './routes/funds.$id'
import { Route as ApiTournamentsRouteImport } from './routes/api/tournaments'
import { Route as ApiThesesRouteImport } from './routes/api/theses'
import { Route as ApiContributorsRouteImport } from './routes/api/contributors'
import { Route as DashboardWriteRouteImport } from './routes/_dashboard/write'
import { Route as DashboardTournamentsRouteImport } from './routes/_dashboard/tournaments'
import { Route as DashboardTalentRouteImport } from './routes/_dashboard/talent'
import { Route as DashboardStocksRouteImport } from './routes/_dashboard/stocks'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardResearchRouteImport } from './routes/_dashboard/research'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardJobsRouteImport } from './routes/_dashboard/jobs'
import { Route as DashboardHistoryRouteImport } from './routes/_dashboard/history'
import { Route as DashboardFundsRouteImport } from './routes/_dashboard/funds'
import { Route as DashboardFundIntelligenceRouteImport } from './routes/_dashboard/fund-intelligence'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardCommunityRouteImport } from './routes/_dashboard/community'
import { Route as DashboardChatsRouteImport } from './routes/_dashboard/chats'
import { Route as ProfilesIdTradesRouteImport } from './routes/profiles.$id.trades'
import { Route as ProfilesIdPerformanceRouteImport } from './routes/profiles.$id.performance'
import { Route as ApiUsersUpdateNameRouteImport } from './routes/api/users/update-name'
import { Route as ApiProfilesIdRouteImport } from './routes/api/profiles/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardPostPostIdRouteImport } from './routes/_dashboard/post.$postId'
import { Route as DashboardChatSessionIdRouteImport } from './routes/_dashboard/chat.$sessionId'
import { Route as ApiProfilesIdTradeHistoryRouteImport } from './routes/api/profiles/$id/trade-history'
import { Route as ApiProfilesIdPerformanceRouteImport } from './routes/api/profiles/$id/performance'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedRoute = SeedRouteImport.update({
  id: '/seed',
  path: '/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const SanityRoute = SanityRouteImport.update({
  id: '/sanity',
  path: '/sanity',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugSimpleRoute = DebugSimpleRouteImport.update({
  id: '/debug-simple',
  path: '/debug-simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugDbRoute = DebugDbRouteImport.update({
  id: '/debug-db',
  path: '/debug-db',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporationsIndexRoute = CorporationsIndexRouteImport.update({
  id: '/corporations/',
  path: '/corporations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIdRoute = ProfilesIdRouteImport.update({
  id: '/profiles/$id',
  path: '/profiles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsIdRoute = FundsIdRouteImport.update({
  id: '/funds/$id',
  path: '/funds/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTournamentsRoute = ApiTournamentsRouteImport.update({
  id: '/api/tournaments',
  path: '/api/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThesesRoute = ApiThesesRouteImport.update({
  id: '/api/theses',
  path: '/api/theses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContributorsRoute = ApiContributorsRouteImport.update({
  id: '/api/contributors',
  path: '/api/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWriteRoute = DashboardWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTournamentsRoute = DashboardTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTalentRoute = DashboardTalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStocksRoute = DashboardStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResearchRoute = DashboardResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFundsRoute = DashboardFundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFundIntelligenceRoute =
  DashboardFundIntelligenceRouteImport.update({
    id: '/fund-intelligence',
    path: '/fund-intelligence',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommunityRoute = DashboardCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatsRoute = DashboardChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => DashboardRoute,
} as any)
const ProfilesIdTradesRoute = ProfilesIdTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => ProfilesIdRoute,
} as any)
const ProfilesIdPerformanceRoute = ProfilesIdPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => ProfilesIdRoute,
} as any)
const ApiUsersUpdateNameRoute = ApiUsersUpdateNameRouteImport.update({
  id: '/api/users/update-name',
  path: '/api/users/update-name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesIdRoute = ApiProfilesIdRouteImport.update({
  id: '/api/profiles/$id',
  path: '/api/profiles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPostPostIdRoute = DashboardPostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatSessionIdRoute = DashboardChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiProfilesIdTradeHistoryRoute =
  ApiProfilesIdTradeHistoryRouteImport.update({
    id: '/trade-history',
    path: '/trade-history',
    getParentRoute: () => ApiProfilesIdRoute,
  } as any)
const ApiProfilesIdPerformanceRoute =
  ApiProfilesIdPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => ApiProfilesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug-db': typeof DebugDbRoute
  '/debug-simple': typeof DebugSimpleRoute
  '/login': typeof LoginRoute
  '/sanity': typeof SanityRoute
  '/seed': typeof SeedRoute
  '/signup': typeof SignupRoute
  '/chats': typeof DashboardChatsRoute
  '/community': typeof DashboardCommunityRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/fund-intelligence': typeof DashboardFundIntelligenceRoute
  '/funds': typeof DashboardFundsRoute
  '/history': typeof DashboardHistoryRoute
  '/jobs': typeof DashboardJobsRoute
  '/profile': typeof DashboardProfileRoute
  '/research': typeof DashboardResearchRoute
  '/settings': typeof DashboardSettingsRoute
  '/stocks': typeof DashboardStocksRoute
  '/talent': typeof DashboardTalentRoute
  '/tournaments': typeof DashboardTournamentsRoute
  '/write': typeof DashboardWriteRoute
  '/api/contributors': typeof ApiContributorsRoute
  '/api/theses': typeof ApiThesesRoute
  '/api/tournaments': typeof ApiTournamentsRoute
  '/funds/$id': typeof FundsIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/profiles/$id': typeof ProfilesIdRouteWithChildren
  '/corporations': typeof CorporationsIndexRoute
  '/chat/$sessionId': typeof DashboardChatSessionIdRoute
  '/post/$postId': typeof DashboardPostPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/profiles/$id': typeof ApiProfilesIdRouteWithChildren
  '/api/users/update-name': typeof ApiUsersUpdateNameRoute
  '/profiles/$id/performance': typeof ProfilesIdPerformanceRoute
  '/profiles/$id/trades': typeof ProfilesIdTradesRoute
  '/api/profiles/$id/performance': typeof ApiProfilesIdPerformanceRoute
  '/api/profiles/$id/trade-history': typeof ApiProfilesIdTradeHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug-db': typeof DebugDbRoute
  '/debug-simple': typeof DebugSimpleRoute
  '/login': typeof LoginRoute
  '/sanity': typeof SanityRoute
  '/seed': typeof SeedRoute
  '/signup': typeof SignupRoute
  '/chats': typeof DashboardChatsRoute
  '/community': typeof DashboardCommunityRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/fund-intelligence': typeof DashboardFundIntelligenceRoute
  '/funds': typeof DashboardFundsRoute
  '/history': typeof DashboardHistoryRoute
  '/jobs': typeof DashboardJobsRoute
  '/profile': typeof DashboardProfileRoute
  '/research': typeof DashboardResearchRoute
  '/settings': typeof DashboardSettingsRoute
  '/stocks': typeof DashboardStocksRoute
  '/talent': typeof DashboardTalentRoute
  '/tournaments': typeof DashboardTournamentsRoute
  '/write': typeof DashboardWriteRoute
  '/api/contributors': typeof ApiContributorsRoute
  '/api/theses': typeof ApiThesesRoute
  '/api/tournaments': typeof ApiTournamentsRoute
  '/funds/$id': typeof FundsIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/profiles/$id': typeof ProfilesIdRouteWithChildren
  '/corporations': typeof CorporationsIndexRoute
  '/chat/$sessionId': typeof DashboardChatSessionIdRoute
  '/post/$postId': typeof DashboardPostPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/profiles/$id': typeof ApiProfilesIdRouteWithChildren
  '/api/users/update-name': typeof ApiUsersUpdateNameRoute
  '/profiles/$id/performance': typeof ProfilesIdPerformanceRoute
  '/profiles/$id/trades': typeof ProfilesIdTradesRoute
  '/api/profiles/$id/performance': typeof ApiProfilesIdPerformanceRoute
  '/api/profiles/$id/trade-history': typeof ApiProfilesIdTradeHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/debug-db': typeof DebugDbRoute
  '/debug-simple': typeof DebugSimpleRoute
  '/login': typeof LoginRoute
  '/sanity': typeof SanityRoute
  '/seed': typeof SeedRoute
  '/signup': typeof SignupRoute
  '/_dashboard/chats': typeof DashboardChatsRoute
  '/_dashboard/community': typeof DashboardCommunityRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/fund-intelligence': typeof DashboardFundIntelligenceRoute
  '/_dashboard/funds': typeof DashboardFundsRoute
  '/_dashboard/history': typeof DashboardHistoryRoute
  '/_dashboard/jobs': typeof DashboardJobsRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/research': typeof DashboardResearchRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/stocks': typeof DashboardStocksRoute
  '/_dashboard/talent': typeof DashboardTalentRoute
  '/_dashboard/tournaments': typeof DashboardTournamentsRoute
  '/_dashboard/write': typeof DashboardWriteRoute
  '/api/contributors': typeof ApiContributorsRoute
  '/api/theses': typeof ApiThesesRoute
  '/api/tournaments': typeof ApiTournamentsRoute
  '/funds/$id': typeof FundsIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/profiles/$id': typeof ProfilesIdRouteWithChildren
  '/corporations/': typeof CorporationsIndexRoute
  '/_dashboard/chat/$sessionId': typeof DashboardChatSessionIdRoute
  '/_dashboard/post/$postId': typeof DashboardPostPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/profiles/$id': typeof ApiProfilesIdRouteWithChildren
  '/api/users/update-name': typeof ApiUsersUpdateNameRoute
  '/profiles/$id/performance': typeof ProfilesIdPerformanceRoute
  '/profiles/$id/trades': typeof ProfilesIdTradesRoute
  '/api/profiles/$id/performance': typeof ApiProfilesIdPerformanceRoute
  '/api/profiles/$id/trade-history': typeof ApiProfilesIdTradeHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug-db'
    | '/debug-simple'
    | '/login'
    | '/sanity'
    | '/seed'
    | '/signup'
    | '/chats'
    | '/community'
    | '/dashboard'
    | '/fund-intelligence'
    | '/funds'
    | '/history'
    | '/jobs'
    | '/profile'
    | '/research'
    | '/settings'
    | '/stocks'
    | '/talent'
    | '/tournaments'
    | '/write'
    | '/api/contributors'
    | '/api/theses'
    | '/api/tournaments'
    | '/funds/$id'
    | '/posts/$id'
    | '/posts/$slug'
    | '/profiles/$id'
    | '/corporations'
    | '/chat/$sessionId'
    | '/post/$postId'
    | '/api/auth/$'
    | '/api/profiles/$id'
    | '/api/users/update-name'
    | '/profiles/$id/performance'
    | '/profiles/$id/trades'
    | '/api/profiles/$id/performance'
    | '/api/profiles/$id/trade-history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug-db'
    | '/debug-simple'
    | '/login'
    | '/sanity'
    | '/seed'
    | '/signup'
    | '/chats'
    | '/community'
    | '/dashboard'
    | '/fund-intelligence'
    | '/funds'
    | '/history'
    | '/jobs'
    | '/profile'
    | '/research'
    | '/settings'
    | '/stocks'
    | '/talent'
    | '/tournaments'
    | '/write'
    | '/api/contributors'
    | '/api/theses'
    | '/api/tournaments'
    | '/funds/$id'
    | '/posts/$id'
    | '/posts/$slug'
    | '/profiles/$id'
    | '/corporations'
    | '/chat/$sessionId'
    | '/post/$postId'
    | '/api/auth/$'
    | '/api/profiles/$id'
    | '/api/users/update-name'
    | '/profiles/$id/performance'
    | '/profiles/$id/trades'
    | '/api/profiles/$id/performance'
    | '/api/profiles/$id/trade-history'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/debug-db'
    | '/debug-simple'
    | '/login'
    | '/sanity'
    | '/seed'
    | '/signup'
    | '/_dashboard/chats'
    | '/_dashboard/community'
    | '/_dashboard/dashboard'
    | '/_dashboard/fund-intelligence'
    | '/_dashboard/funds'
    | '/_dashboard/history'
    | '/_dashboard/jobs'
    | '/_dashboard/profile'
    | '/_dashboard/research'
    | '/_dashboard/settings'
    | '/_dashboard/stocks'
    | '/_dashboard/talent'
    | '/_dashboard/tournaments'
    | '/_dashboard/write'
    | '/api/contributors'
    | '/api/theses'
    | '/api/tournaments'
    | '/funds/$id'
    | '/posts/$id'
    | '/posts/$slug'
    | '/profiles/$id'
    | '/corporations/'
    | '/_dashboard/chat/$sessionId'
    | '/_dashboard/post/$postId'
    | '/api/auth/$'
    | '/api/profiles/$id'
    | '/api/users/update-name'
    | '/profiles/$id/performance'
    | '/profiles/$id/trades'
    | '/api/profiles/$id/performance'
    | '/api/profiles/$id/trade-history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DebugDbRoute: typeof DebugDbRoute
  DebugSimpleRoute: typeof DebugSimpleRoute
  LoginRoute: typeof LoginRoute
  SanityRoute: typeof SanityRoute
  SeedRoute: typeof SeedRoute
  SignupRoute: typeof SignupRoute
  ApiContributorsRoute: typeof ApiContributorsRoute
  ApiThesesRoute: typeof ApiThesesRoute
  ApiTournamentsRoute: typeof ApiTournamentsRoute
  FundsIdRoute: typeof FundsIdRoute
  PostsIdRoute: typeof PostsIdRoute
  PostsSlugRoute: typeof PostsSlugRoute
  ProfilesIdRoute: typeof ProfilesIdRouteWithChildren
  CorporationsIndexRoute: typeof CorporationsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiProfilesIdRoute: typeof ApiProfilesIdRouteWithChildren
  ApiUsersUpdateNameRoute: typeof ApiUsersUpdateNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seed': {
      id: '/seed'
      path: '/seed'
      fullPath: '/seed'
      preLoaderRoute: typeof SeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanity': {
      id: '/sanity'
      path: '/sanity'
      fullPath: '/sanity'
      preLoaderRoute: typeof SanityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug-simple': {
      id: '/debug-simple'
      path: '/debug-simple'
      fullPath: '/debug-simple'
      preLoaderRoute: typeof DebugSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug-db': {
      id: '/debug-db'
      path: '/debug-db'
      fullPath: '/debug-db'
      preLoaderRoute: typeof DebugDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporations/': {
      id: '/corporations/'
      path: '/corporations'
      fullPath: '/corporations'
      preLoaderRoute: typeof CorporationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$id': {
      id: '/profiles/$id'
      path: '/profiles/$id'
      fullPath: '/profiles/$id'
      preLoaderRoute: typeof ProfilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds/$id': {
      id: '/funds/$id'
      path: '/funds/$id'
      fullPath: '/funds/$id'
      preLoaderRoute: typeof FundsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tournaments': {
      id: '/api/tournaments'
      path: '/api/tournaments'
      fullPath: '/api/tournaments'
      preLoaderRoute: typeof ApiTournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/theses': {
      id: '/api/theses'
      path: '/api/theses'
      fullPath: '/api/theses'
      preLoaderRoute: typeof ApiThesesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contributors': {
      id: '/api/contributors'
      path: '/api/contributors'
      fullPath: '/api/contributors'
      preLoaderRoute: typeof ApiContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/write': {
      id: '/_dashboard/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof DashboardWriteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tournaments': {
      id: '/_dashboard/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof DashboardTournamentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/talent': {
      id: '/_dashboard/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof DashboardTalentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/stocks': {
      id: '/_dashboard/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof DashboardStocksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/research': {
      id: '/_dashboard/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof DashboardResearchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/jobs': {
      id: '/_dashboard/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/history': {
      id: '/_dashboard/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/funds': {
      id: '/_dashboard/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof DashboardFundsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/fund-intelligence': {
      id: '/_dashboard/fund-intelligence'
      path: '/fund-intelligence'
      fullPath: '/fund-intelligence'
      preLoaderRoute: typeof DashboardFundIntelligenceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/community': {
      id: '/_dashboard/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof DashboardCommunityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/chats': {
      id: '/_dashboard/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof DashboardChatsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/profiles/$id/trades': {
      id: '/profiles/$id/trades'
      path: '/trades'
      fullPath: '/profiles/$id/trades'
      preLoaderRoute: typeof ProfilesIdTradesRouteImport
      parentRoute: typeof ProfilesIdRoute
    }
    '/profiles/$id/performance': {
      id: '/profiles/$id/performance'
      path: '/performance'
      fullPath: '/profiles/$id/performance'
      preLoaderRoute: typeof ProfilesIdPerformanceRouteImport
      parentRoute: typeof ProfilesIdRoute
    }
    '/api/users/update-name': {
      id: '/api/users/update-name'
      path: '/api/users/update-name'
      fullPath: '/api/users/update-name'
      preLoaderRoute: typeof ApiUsersUpdateNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/$id': {
      id: '/api/profiles/$id'
      path: '/api/profiles/$id'
      fullPath: '/api/profiles/$id'
      preLoaderRoute: typeof ApiProfilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/post/$postId': {
      id: '/_dashboard/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof DashboardPostPostIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/chat/$sessionId': {
      id: '/_dashboard/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof DashboardChatSessionIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/profiles/$id/trade-history': {
      id: '/api/profiles/$id/trade-history'
      path: '/trade-history'
      fullPath: '/api/profiles/$id/trade-history'
      preLoaderRoute: typeof ApiProfilesIdTradeHistoryRouteImport
      parentRoute: typeof ApiProfilesIdRoute
    }
    '/api/profiles/$id/performance': {
      id: '/api/profiles/$id/performance'
      path: '/performance'
      fullPath: '/api/profiles/$id/performance'
      preLoaderRoute: typeof ApiProfilesIdPerformanceRouteImport
      parentRoute: typeof ApiProfilesIdRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardChatsRoute: typeof DashboardChatsRoute
  DashboardCommunityRoute: typeof DashboardCommunityRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardFundIntelligenceRoute: typeof DashboardFundIntelligenceRoute
  DashboardFundsRoute: typeof DashboardFundsRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardResearchRoute: typeof DashboardResearchRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStocksRoute: typeof DashboardStocksRoute
  DashboardTalentRoute: typeof DashboardTalentRoute
  DashboardTournamentsRoute: typeof DashboardTournamentsRoute
  DashboardWriteRoute: typeof DashboardWriteRoute
  DashboardChatSessionIdRoute: typeof DashboardChatSessionIdRoute
  DashboardPostPostIdRoute: typeof DashboardPostPostIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChatsRoute: DashboardChatsRoute,
  DashboardCommunityRoute: DashboardCommunityRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardFundIntelligenceRoute: DashboardFundIntelligenceRoute,
  DashboardFundsRoute: DashboardFundsRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardResearchRoute: DashboardResearchRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStocksRoute: DashboardStocksRoute,
  DashboardTalentRoute: DashboardTalentRoute,
  DashboardTournamentsRoute: DashboardTournamentsRoute,
  DashboardWriteRoute: DashboardWriteRoute,
  DashboardChatSessionIdRoute: DashboardChatSessionIdRoute,
  DashboardPostPostIdRoute: DashboardPostPostIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ProfilesIdRouteChildren {
  ProfilesIdPerformanceRoute: typeof ProfilesIdPerformanceRoute
  ProfilesIdTradesRoute: typeof ProfilesIdTradesRoute
}

const ProfilesIdRouteChildren: ProfilesIdRouteChildren = {
  ProfilesIdPerformanceRoute: ProfilesIdPerformanceRoute,
  ProfilesIdTradesRoute: ProfilesIdTradesRoute,
}

const ProfilesIdRouteWithChildren = ProfilesIdRoute._addFileChildren(
  ProfilesIdRouteChildren,
)

interface ApiProfilesIdRouteChildren {
  ApiProfilesIdPerformanceRoute: typeof ApiProfilesIdPerformanceRoute
  ApiProfilesIdTradeHistoryRoute: typeof ApiProfilesIdTradeHistoryRoute
}

const ApiProfilesIdRouteChildren: ApiProfilesIdRouteChildren = {
  ApiProfilesIdPerformanceRoute: ApiProfilesIdPerformanceRoute,
  ApiProfilesIdTradeHistoryRoute: ApiProfilesIdTradeHistoryRoute,
}

const ApiProfilesIdRouteWithChildren = ApiProfilesIdRoute._addFileChildren(
  ApiProfilesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DebugDbRoute: DebugDbRoute,
  DebugSimpleRoute: DebugSimpleRoute,
  LoginRoute: LoginRoute,
  SanityRoute: SanityRoute,
  SeedRoute: SeedRoute,
  SignupRoute: SignupRoute,
  ApiContributorsRoute: ApiContributorsRoute,
  ApiThesesRoute: ApiThesesRoute,
  ApiTournamentsRoute: ApiTournamentsRoute,
  FundsIdRoute: FundsIdRoute,
  PostsIdRoute: PostsIdRoute,
  PostsSlugRoute: PostsSlugRoute,
  ProfilesIdRoute: ProfilesIdRouteWithChildren,
  CorporationsIndexRoute: CorporationsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiProfilesIdRoute: ApiProfilesIdRouteWithChildren,
  ApiUsersUpdateNameRoute: ApiUsersUpdateNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
